import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import me from "./me2.jpg"
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> 
     
      <header className="text-white body-font bg-orange-950">
  <div className="container mx-auto flex flex-wrap p-4 flex-col md:flex-row items-center">
    <a className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
    <div className="avatar">
  <div className="ring-primary ring-offset-base-100 w-20 rounded-full ring ring-offset-2">
   <Image src = {me} alt = "me"></Image>
  </div>
</div>
      <h1 className="ml-3 text-4xl font-serif font-bold text-white hover:text-pink-600 animate-bounce hover:uppercase"><span className="text-pink-600 text-5xl hover:text-white">P</span>ortFolio</h1>
    </a>
    <nav className="md:ml-auto md:mr-auto flex flex-wrap items-center justify-center text-2xl gap-7 font-sans font-semibold animate-pulse">
      <Link href="/" className="mr-5  transform hover:scale-110 motion-reduce:transform-none hover:text-pink-600 hover:uppercase">Home</Link>
      <Link href="/about" className="mr-5 transform hover:scale-110 motion-reduce:transform-none hover:text-pink-600 hover:uppercase">About</Link>
      <Link href="/skills" className="mr-5 transform hover:scale-110 motion-reduce:transform-none hover:text-pink-600 hover:uppercase">Skills</Link>
      <Link href="/projects" className="mr-5 transform hover:scale-110 motion-reduce:transform-none hover:text-pink-600 hover:uppercase">Projects</Link>
      <Link href="/services" className="mr-5 transform hover:scale-110 motion-reduce:transform-none hover:text-pink-600 hover:uppercase">Services</Link>
      <Link href="/contact" className="mr-5 transform hover:scale-110 motion-reduce:transform-none hover:text-pink-600 hover:uppercase">Contact</Link>
    </nav>
  </div>
</header>
        {children}
        <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1" async></script>
<df-messenger
  chat-icon="https:&#x2F;&#x2F;upload.wikimedia.org&#x2F;wikipedia&#x2F;commons&#x2F;0&#x2F;04&#x2F;ChatGPT_logo.svg"
  intent="WELCOME"
  chat-title="portfolio-chatbot"
  agent-id="06911b46-c7dc-49fc-8747-349a9c1bd289"
  language-code="en"
></df-messenger>
        </body>
    </html>
  );
}
